/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;

/**
 *
 * @author c.perrat
 */
public class MainView extends javax.swing.JFrame {
    
    private SalarieView salarieView = new SalarieView();
    private ServiceView serviceView = new ServiceView();
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        
        this.mainPanel.add(this.serviceView, "cardService");
        this.mainPanel.add(this.salarieView, "cardSalarie");
    }
    
    public SalarieView getSalarieView() {
        return this.salarieView;
    }
    
    public ServiceView getServiceView() {
        return this.serviceView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        salarieMenu = new javax.swing.JMenu();
        salarieItem = new javax.swing.JMenuItem();
        serviceItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        salarieMenu.setText("Afficher");

        salarieItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        salarieItem.setText("Salariés");
        salarieItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarieItemActionPerformed(evt);
            }
        });
        salarieMenu.add(salarieItem);

        serviceItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        serviceItem.setText("Services");
        serviceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceItemActionPerformed(evt);
            }
        });
        salarieMenu.add(serviceItem);

        jMenuBar1.add(salarieMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serviceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceItemActionPerformed
        // TODO add your handling code here:
        
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "cardService");
    }//GEN-LAST:event_serviceItemActionPerformed

    private void salarieItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarieItemActionPerformed
        // TODO add your handling code here:
        
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "cardSalarie");
    }//GEN-LAST:event_salarieItemActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem salarieItem;
    private javax.swing.JMenu salarieMenu;
    private javax.swing.JMenuItem serviceItem;
    // End of variables declaration//GEN-END:variables
}
