/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import model.SalarieTableModel;

/**
 *
 * @author c.perrat
 */
public class SalarieView extends javax.swing.JPanel {

    private PropertyChangeSupport listeners;

    /**
     * Creates new form SalariePan
     */
    public SalarieView() {
        initComponents();

        this.listeners = new PropertyChangeSupport(this);
    }

    public void addPropertyChangeListener(PropertyChangeListener l) {
        listeners.addPropertyChangeListener(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableSalaries = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSupprSalarie = new javax.swing.JButton();
        btnAjoutSalarie = new javax.swing.JButton();
        btnModifSalarie = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(740, 363));

        tableSalaries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Prénom", "Fonction", "Date de naissance", "Service"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSalaries.setRowHeight(24);
        jScrollPane1.setViewportView(tableSalaries);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Liste des salariés");

        btnSupprSalarie.setText("Supprimer");

        btnAjoutSalarie.setText("Ajouter");
        btnAjoutSalarie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutSalarieActionPerformed(evt);
            }
        });

        btnModifSalarie.setText("Modifier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(264, 264, 264))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAjoutSalarie)
                        .addGap(34, 34, 34)
                        .addComponent(btnModifSalarie)
                        .addGap(35, 35, 35)
                        .addComponent(btnSupprSalarie)
                        .addGap(195, 195, 195))))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupprSalarie)
                    .addComponent(btnAjoutSalarie)
                    .addComponent(btnModifSalarie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjoutSalarieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutSalarieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjoutSalarieActionPerformed

    public void hideSalarieIdColumn() {
        this.tableSalaries.removeColumn(this.tableSalaries.getColumnModel().getColumn(0));
    }
    
    public void setSalarieTableModel(SalarieTableModel salarieTableModel){
        this.tableSalaries.setModel(salarieTableModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjoutSalarie;
    private javax.swing.JButton btnModifSalarie;
    private javax.swing.JButton btnSupprSalarie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSalaries;
    // End of variables declaration//GEN-END:variables
}
