/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import model.SalarieTableModel;
import model.Service;
import model.ServiceComboBoxModel;

/**
 *
 * @author c.perrat
 */
public class SalarieView extends javax.swing.JPanel {

    private PropertyChangeSupport listeners;
    private SalarieEditPanel salarieEditPanel;
    private SupprPanel supprPan;

    /**
     * Creates new form SalariePan
     */
    public SalarieView() {
        initComponents();

        this.listeners = new PropertyChangeSupport(this);
        this.supprPan = new SupprPanel();
        salarieEditPanel = new SalarieEditPanel();
    }

    public void addPropertyChangeListener(PropertyChangeListener l) {
        listeners.addPropertyChangeListener(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableSalaries = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSupprSalarie = new javax.swing.JButton();
        btnAjoutSalarie = new javax.swing.JButton();
        btnModifSalarie = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(740, 363));

        tableSalaries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Prénom", "Fonction", "Date de naissance", "Service", "ServiceNom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSalaries.setRowHeight(24);
        jScrollPane1.setViewportView(tableSalaries);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Liste des salariés");

        btnSupprSalarie.setText("Supprimer");
        btnSupprSalarie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprSalarieActionPerformed(evt);
            }
        });

        btnAjoutSalarie.setText("Ajouter");
        btnAjoutSalarie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutSalarieActionPerformed(evt);
            }
        });

        btnModifSalarie.setText("Modifier");
        btnModifSalarie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifSalarieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAjoutSalarie)
                .addGap(35, 35, 35)
                .addComponent(btnModifSalarie)
                .addGap(35, 35, 35)
                .addComponent(btnSupprSalarie)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupprSalarie)
                    .addComponent(btnAjoutSalarie)
                    .addComponent(btnModifSalarie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjoutSalarieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutSalarieActionPerformed
        listeners.firePropertyChange("openAjoutSalarie", null, null);
    }//GEN-LAST:event_btnAjoutSalarieActionPerformed

    private void btnModifSalarieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifSalarieActionPerformed
        if (this.tableSalaries.getSelectedRow() > -1) listeners.firePropertyChange("openModifSalarie", null, null);
    }//GEN-LAST:event_btnModifSalarieActionPerformed

    private void btnSupprSalarieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprSalarieActionPerformed
       this.listeners.firePropertyChange("openSupprSalarie", null, null);
    }//GEN-LAST:event_btnSupprSalarieActionPerformed

    public void hideSalarieIdColumn() {
        this.tableSalaries.removeColumn(this.tableSalaries.getColumnModel().getColumn(0));
    }
    
    public void hideServiceIdColumn() {
        this.tableSalaries.removeColumn(this.tableSalaries.getColumnModel().getColumn(5));
    }
    
    public void setSalarieTableModel(SalarieTableModel salarieTableModel){
        this.tableSalaries.setModel(salarieTableModel);
    }
    
    public void setSalarieComboBoxModel(ServiceComboBoxModel serviceComboBoxModel){
        this.salarieEditPanel.setSalarieComboBoxModel(serviceComboBoxModel);
    }
    
    public String getSalNom(){
        return this.salarieEditPanel.getNom();
    }
    
    public String getSalPrenom(){
        return this.salarieEditPanel.getPrenom();
    }
    
    public String getSalFonction(){
        return this.salarieEditPanel.getFonction();
    }
    
    public String getSalDate(){
        
        return this.salarieEditPanel.getDate();
    }
    
    public int getSalServiceIndex(){
        return this.salarieEditPanel.getServiceIndex();
    }
    
    public int getSelectedId() {
        int row = this.tableSalaries.getSelectedRow();
        return Integer.parseInt(this.tableSalaries.getModel().getValueAt(row, 0).toString());
    }
    
   public void setSalarieNom(String nom){
       this.salarieEditPanel.setNomText(nom);
   }
   
   public void setSalariePrenom(String prenom){
       this.salarieEditPanel.setPrenomText(prenom);
   }
   
   public void setSalarieFonction(String fonction){
       this.salarieEditPanel.setFonctionText(fonction);
   }
   
   public void setSalarieDateNaissance(String date){
       this.salarieEditPanel.setDateNaissanceText(date);
   }
   
   public void setSelectedService(Service service){
       this.salarieEditPanel.setSelectedService(service);
   }
   
   public void setPanelLabel(String nom){
       this.salarieEditPanel.setPanelLabel(nom);
   }
   
   
    
    public String[] getSelectedSalarieRow() {
        int row = this.tableSalaries.getSelectedRow();
        String id = this.tableSalaries.getModel().getValueAt(row, 0).toString();
        String nom = this.tableSalaries.getModel().getValueAt(row, 1).toString();
        String prenom = this.tableSalaries.getModel().getValueAt(row, 2).toString();
        String fonction = this.tableSalaries.getModel().getValueAt(row, 3).toString();
        String date = this.tableSalaries.getModel().getValueAt(row, 4).toString();
        String serviceId = this.tableSalaries.getModel().getValueAt(row, 5).toString();
        String[] selected = {id, nom, prenom,fonction,date,serviceId};

        return selected;
    }
    
    public void openAjoutSal() {
        String[] options = {"Valider", "Annuler"};
        

        // La méthode la plus générale pour ouvrir une boite de dialogue...
        int result = JOptionPane.showOptionDialog(
                this, // le composant parent de la boite (ici, le JFrame)
                this.salarieEditPanel, // contenu de la boite (ici, JPanel défini ailleurs)
                "Ajout d'un nouveau salarié", // le titre de la boite
                JOptionPane.OK_CANCEL_OPTION, // boutons à afficher (cf constantes JOptionPane)
                JOptionPane.PLAIN_MESSAGE, // style du message
                null, // pas d'icone à afficher
                options, // texte des boutons
                options[0] // bouton par défaut
        );

        if (result == JOptionPane.OK_OPTION) { // si l'utilisateur a validé...
            // ...envoi de la notification "validAjoutModifEtudiant" au contrôleur
            listeners.firePropertyChange("validAjoutSalarie", null, null);
        }
    }
    
    public void openModifSal(){
       String[] options = {"Valider", "Annuler"};
        
        // La méthode la plus générale pour ouvrir une boite de dialogue...
        int result = JOptionPane.showOptionDialog(
                this, // le composant parent de la boite (ici, le JFrame)
                this.salarieEditPanel, // contenu de la boite (ici, JPanel défini ailleurs)
                "Modification d'un nouveau salarié", // le titre de la boite
                JOptionPane.OK_CANCEL_OPTION, // boutons à afficher (cf constantes JOptionPane)
                JOptionPane.PLAIN_MESSAGE, // style du message
                null, // pas d'icone à afficher
                options, // texte des boutons
                options[0] // bouton par défaut
        );

        if (result == JOptionPane.OK_OPTION) { // si l'utilisateur a validé...
            // ...envoi de la notification "validAjoutModifEtudiant" au contrôleur
            listeners.firePropertyChange("validModifSalarie", null, null);
        } 
    }
    
    public void openSupprDialog() {
        String[] options = {"Oui", "Non"};

        UIManager.put("OptionPane.buttonOrientation", SwingConstants.CENTER);

        int result = JOptionPane.showOptionDialog(
                this,
                this.supprPan,
                null,
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE,
                null,
                options,
                options[0]
        );

        if (result == JOptionPane.OK_OPTION) {
            listeners.firePropertyChange("validSupprSalarie", null, null);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjoutSalarie;
    private javax.swing.JButton btnModifSalarie;
    private javax.swing.JButton btnSupprSalarie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSalaries;
    // End of variables declaration//GEN-END:variables
}
