/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JRadioButton;

/**
 *
 * @author c.perrat
 */
public class ServiceEditPanel extends javax.swing.JPanel {

    /**
     * Creates new form ServiceEditPanel
     */
    public ServiceEditPanel() {
        initComponents();
        this.adminiTrue.setActionCommand("true");
        this.adminiFalse.setActionCommand("false");
    }
    
    public int getIsAdmini() {
        String isAdmini = this.adminiBtnGroup.getSelection().getActionCommand();
        if (isAdmini == "true") {
            return 1;
        } else {
            return 0;
        }
    }
    
    public String getNameService() {
        return this.serviceNameInput.getText();
    }

    public void setIsAdmini(boolean isA) {  
        if (isA == true) {
            this.adminiFalse.setSelected(false);
            this.adminiTrue.setSelected(true);
        } else {
            this.adminiTrue.setSelected(false);
            this.adminiFalse.setSelected(true);
        }
    }
    
    public void clearAdmini() {
        this.adminiBtnGroup.clearSelection();
    }
    
    public void setServiceNameInput(String name) {
        this.serviceNameInput.setText(name);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminiBtnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        serviceNameInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        adminiTrue = new javax.swing.JRadioButton();
        adminiFalse = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Nom :");

        serviceNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceNameInputActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Administratif :");

        adminiBtnGroup.add(adminiTrue);
        adminiTrue.setText("Oui");
        adminiTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminiTrueActionPerformed(evt);
            }
        });

        adminiBtnGroup.add(adminiFalse);
        adminiFalse.setText("Non");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminiTrue)
                        .addGap(18, 18, 18)
                        .addComponent(adminiFalse))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serviceNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(serviceNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(adminiTrue)
                    .addComponent(adminiFalse))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void serviceNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceNameInputActionPerformed

    private void adminiTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminiTrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminiTrueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup adminiBtnGroup;
    private javax.swing.JRadioButton adminiFalse;
    private javax.swing.JRadioButton adminiTrue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField serviceNameInput;
    // End of variables declaration//GEN-END:variables
}
