/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import model.ServiceTableModel;

/**
 *
 * @author c.perrat
 */
public class ServiceView extends javax.swing.JPanel {

    private PropertyChangeSupport listeners;

    private ServiceEditPanel srvEditPan;
    
    private SupprPanel supprPan;

    /**
     * Creates new form ServicePan
     */
    public ServiceView() {
        initComponents();

        this.srvEditPan = new ServiceEditPanel();
        this.supprPan = new SupprPanel();
        this.listeners = new PropertyChangeSupport(this);
    }

    public String getSrvName() {
        return this.srvEditPan.getNameService();
    }

    public int getSrvIsAdmini() {
        return this.srvEditPan.getIsAdmini();
    }

    public void setModifIsAdmini(int isA) {
        this.srvEditPan.setIsAdmini(isA == 1 ? true : false);
    }

    public void setModifName(String name) {
        this.srvEditPan.setServiceNameInput(name);
    }

    public String[] getSelectedServiceRow() {
        int row = this.serviceTable.getSelectedRow();
        String id = this.serviceTable.getModel().getValueAt(row, 0).toString();
        String name = this.serviceTable.getModel().getValueAt(row, 1).toString();
        String is = this.serviceTable.getModel().getValueAt(row, 2).toString();
        String[] selected = {id, name, is};

        return selected;
    }

    public int getSelectedId() {
        int row = this.serviceTable.getSelectedRow();
        return Integer.parseInt(this.serviceTable.getModel().getValueAt(row, 0).toString());
    }

    public void openDialogueEditSrv(String editMeth) {
        String[] options = {editMeth == "ajout" ? "Ajouter" : "Modifier", "Annuler"};

        UIManager.put("OptionPane.buttonOrientation", SwingConstants.CENTER);

        int result = JOptionPane.showOptionDialog(
                this,
                this.srvEditPan,
                editMeth == "ajout" ? "Ajout d'un nouveau service" : "Modification d'un service",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE,
                null,
                options,
                options[0]
        );

        if (result == JOptionPane.OK_OPTION) {
            if (editMeth == "ajout") {
                listeners.firePropertyChange("validAjoutService", null, null);
            } else {
                listeners.firePropertyChange("validModifService", null, null);
            }
            this.srvEditPan.setServiceNameInput("");
            this.srvEditPan.clearAdmini();
        }
    }
    
    public void openSupprDialog() {
        String[] options = {"Oui", "Non"};

        UIManager.put("OptionPane.buttonOrientation", SwingConstants.CENTER);

        int result = JOptionPane.showOptionDialog(
                this,
                this.supprPan,
                null,
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE,
                null,
                options,
                options[0]
        );

        if (result == JOptionPane.OK_OPTION) {
            listeners.firePropertyChange("validSupprService", null, null);
        }
    }

    public void addPropertyChangeListener(PropertyChangeListener l) {
        listeners.addPropertyChangeListener(l);
    }

    public void setServiceTableModel(ServiceTableModel serTableModel) {
        this.serviceTable.setModel(serTableModel);
    }

    public void hideColumn() {
        this.serviceTable.removeColumn(this.serviceTable.getColumnModel().getColumn(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        serviceTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAjoutService = new javax.swing.JButton();
        btnModifService = new javax.swing.JButton();
        btnSupprService = new javax.swing.JButton();

        serviceTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        serviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Nom", "Administratif"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        serviceTable.setRowHeight(24);
        serviceTable.getTableHeader().setResizingAllowed(false);
        serviceTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(serviceTable);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liste des services");

        btnAjoutService.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAjoutService.setText("Ajouter");
        btnAjoutService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutServiceActionPerformed(evt);
            }
        });

        btnModifService.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnModifService.setText("Modifier");
        btnModifService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifServiceActionPerformed(evt);
            }
        });

        btnSupprService.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSupprService.setText("Supprimer");
        btnSupprService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnModifService, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAjoutService, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSupprService, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifService)
                    .addComponent(btnSupprService)
                    .addComponent(btnAjoutService))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjoutServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutServiceActionPerformed
        // TODO add your handling code here:
        this.listeners.firePropertyChange("AjoutService", null, null);
    }//GEN-LAST:event_btnAjoutServiceActionPerformed

    private void btnModifServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifServiceActionPerformed
        // TODO add your handling code here:
        if (this.serviceTable.getSelectedRow() > -1) this.listeners.firePropertyChange("ModifService", null, null);
    }//GEN-LAST:event_btnModifServiceActionPerformed

    private void btnSupprServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprServiceActionPerformed
        // TODO add your handling code here:
        this.listeners.firePropertyChange("SupprService", null, null);
    }//GEN-LAST:event_btnSupprServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjoutService;
    private javax.swing.JButton btnModifService;
    private javax.swing.JButton btnSupprService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable serviceTable;
    // End of variables declaration//GEN-END:variables

}
